/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#60ff99",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#b9cbb9",
        "on-secondary-fixed-variant": "#005228",
        "on-error-container": "#ffdad6",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-container-highest": "#353534",
        "primary": "#f1ffef",
        "surface-bright": "#3a3939",
        "on-background": "#e5e2e1",
        "secondary-container": "#027038",
        "primary-container": "#00ff88",
        "error": "#ffb4ab",
        "secondary-fixed": "#9af7b0",
        "secondary": "#7eda96",
        "surface": "#131313",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#e5c364",
        "on-primary-fixed-variant": "#005228",
        "primary-fixed-dim": "#00e479",
        "on-primary-container": "#007139",
        "outline-variant": "#3b4b3d",
        "on-secondary-fixed": "#00210c",
        "tertiary-fixed": "#ffe08d",
        "on-primary": "#003919",
        "on-tertiary": "#3d2f00",
        "on-error": "#690005",
        "error-container": "#93000a",
        "inverse-on-surface": "#313030",
        "on-secondary": "#003919",
        "on-secondary-container": "#94f0ab",
        "surface-container": "#201f1f",
        "tertiary-container": "#ffdb79",
        "on-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#584400",
        "outline": "#849585",
        "on-tertiary-fixed": "#241a00",
        "surface-tint": "#00e479",
        "secondary-fixed-dim": "#7eda96",
        "surface-container-low": "#1c1b1b",
        "background": "#131313",
        "inverse-primary": "#006d37",
        "on-primary-fixed": "#00210c",
        "tertiary": "#fffaf7",
        "on-tertiary-container": "#795f01"
      },
      fontFamily: {
        "headline": ["Epilogue"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
}
